// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcBYWdV7EkBocNvN_I679T4aehvUVwWYM',
    appId: '1:206509253761:web:46738197aef331d2e65980',
    messagingSenderId: '206509253761',
    projectId: 'nimbus-7e0eb',
    authDomain: 'nimbus-7e0eb.firebaseapp.com',
    storageBucket: 'nimbus-7e0eb.appspot.com',
    measurementId: 'G-02D2TQ2X6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWLaIRtPZns_DIK3F60TgXe7fuDoYY12g',
    appId: '1:206509253761:android:3a6db5396a46387ae65980',
    messagingSenderId: '206509253761',
    projectId: 'nimbus-7e0eb',
    storageBucket: 'nimbus-7e0eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ8bJ_MmNmvy-CK1gi5aO8al6KoES7MRE',
    appId: '1:206509253761:ios:12f0a621a10dd610e65980',
    messagingSenderId: '206509253761',
    projectId: 'nimbus-7e0eb',
    storageBucket: 'nimbus-7e0eb.appspot.com',
    iosBundleId: 'com.example.voyzon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ8bJ_MmNmvy-CK1gi5aO8al6KoES7MRE',
    appId: '1:206509253761:ios:1094406de439b2dee65980',
    messagingSenderId: '206509253761',
    projectId: 'nimbus-7e0eb',
    storageBucket: 'nimbus-7e0eb.appspot.com',
    iosBundleId: 'com.example.voyzon.RunnerTests',
  );
}
